import Home from "./Home"
import SignUp from "./SignUp"
import Login from "./Login"
import CreateEvent from "./CreateEvent"
import JoinEvent from "./JoinEvent"
import LookForPlayer from "./LookForPlayer"
import PlayerProfile from "./PlayerProfile"
import FriendsList from "./friendsList"
import ChatPage from "./ChatPage"
export { Home, SignUp, Login, CreateEvent, JoinEvent, LookForPlayer, PlayerProfile,FriendsList,ChatPage }
